// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PrisonManagement.Data;

#nullable disable

namespace PrisonManagement.Migrations
{
    [DbContext(typeof(PrisonDbContext))]
    partial class PrisonDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PrisonManagement.Models.CanBo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ChucVu")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("DiaChi")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("GioiTinh")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MaCanBo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("NgaySinh")
                        .HasColumnType("datetime2");

                    b.Property<string>("PhongPhuTrach")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("SDT")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("TaiKhoanId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MaCanBo")
                        .IsUnique();

                    b.HasIndex("TaiKhoanId")
                        .IsUnique()
                        .HasFilter("[TaiKhoanId] IS NOT NULL");

                    b.ToTable("CanBo");
                });

            modelBuilder.Entity("PrisonManagement.Models.KhenThuong", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("GhiChu")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("HinhThuc")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LyDo")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("NgayKhenThuong")
                        .HasColumnType("datetime2");

                    b.Property<string>("NguoiKy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("PhamNhanId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PhamNhanId");

                    b.ToTable("KhenThuong");
                });

            modelBuilder.Entity("PrisonManagement.Models.KyLuat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("GhiChu")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("HinhThuc")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LyDo")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("NgayKyLuat")
                        .HasColumnType("datetime2");

                    b.Property<string>("NguoiKy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("PhamNhanId")
                        .HasColumnType("int");

                    b.Property<string>("ThoiHan")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("PhamNhanId");

                    b.ToTable("KyLuat");
                });

            modelBuilder.Entity("PrisonManagement.Models.LaoDong", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DanhGia")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("GhiChu")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("KetQua")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("LoaiHoatDong")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("NgayBatDau")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayKetThuc")
                        .HasColumnType("datetime2");

                    b.Property<int>("PhamNhanId")
                        .HasColumnType("int");

                    b.Property<string>("TenHoatDong")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("PhamNhanId");

                    b.ToTable("LaoDong");
                });

            modelBuilder.Entity("PrisonManagement.Models.LichSuTruyCap", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ChiTiet")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("DiaChi_IP")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("HanhDong")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("TaiKhoanId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ThoiGian")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("TaiKhoanId");

                    b.ToTable("LichSuTruyCap");
                });

            modelBuilder.Entity("PrisonManagement.Models.PhamNhan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("GioiTinh")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MaPhamNhan")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("NgayRaTrai")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgaySinh")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayVaoTrai")
                        .HasColumnType("datetime2");

                    b.Property<int>("PhongGiamId")
                        .HasColumnType("int");

                    b.Property<string>("QueQuan")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("ToiDanh")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("MaPhamNhan")
                        .IsUnique();

                    b.HasIndex("PhongGiamId");

                    b.ToTable("PhamNhan");
                });

            modelBuilder.Entity("PrisonManagement.Models.PhongGiam", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("LoaiPhong")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("MaPhong")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("SoLuongHienTai")
                        .HasColumnType("int");

                    b.Property<int>("SucChua")
                        .HasColumnType("int");

                    b.Property<string>("TenPhong")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("MaPhong")
                        .IsUnique();

                    b.ToTable("PhongGiam");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            LoaiPhong = "Bình thường",
                            MaPhong = "A1",
                            SoLuongHienTai = 0,
                            SucChua = 10,
                            TenPhong = "Phòng A1 - Tầng 1",
                            TrangThai = "HoatDong"
                        },
                        new
                        {
                            Id = 2,
                            LoaiPhong = "Bình thường",
                            MaPhong = "A2",
                            SoLuongHienTai = 0,
                            SucChua = 10,
                            TenPhong = "Phòng A2 - Tầng 1",
                            TrangThai = "HoatDong"
                        },
                        new
                        {
                            Id = 3,
                            LoaiPhong = "Đặc biệt",
                            MaPhong = "B1",
                            SoLuongHienTai = 0,
                            SucChua = 8,
                            TenPhong = "Phòng B1 - Tầng 2",
                            TrangThai = "HoatDong"
                        });
                });

            modelBuilder.Entity("PrisonManagement.Models.Quyen", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("MoTa")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("TenQuyen")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Quyen");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            MoTa = "Quản trị viên hệ thống",
                            TenQuyen = "Admin"
                        },
                        new
                        {
                            Id = 2,
                            MoTa = "Cán bộ quản lý",
                            TenQuyen = "CanBo"
                        },
                        new
                        {
                            Id = 3,
                            MoTa = "Giám sát viên",
                            TenQuyen = "GiamSat"
                        });
                });

            modelBuilder.Entity("PrisonManagement.Models.SuCo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BienPhapXuLy")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("GhiChu")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("LoaiSuCo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("MoTa")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("MucDo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("NgayXayRa")
                        .HasColumnType("datetime2");

                    b.Property<string>("NguoiBaoCao")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PhamNhanLienQuan")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.ToTable("SuCo");
                });

            modelBuilder.Entity("PrisonManagement.Models.SucKhoe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BacSi")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ChanDoan")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("DieuTri")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("GhiChu")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("LoaiKham")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("NgayKham")
                        .HasColumnType("datetime2");

                    b.Property<int>("PhamNhanId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PhamNhanId");

                    b.ToTable("SucKhoe");
                });

            modelBuilder.Entity("PrisonManagement.Models.TaiKhoan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("MatKhauHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("QuyenId")
                        .HasColumnType("int");

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("QuyenId");

                    b.HasIndex("Ten")
                        .IsUnique();

                    b.ToTable("TaiKhoan");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsActive = true,
                            MatKhauHash = "admin123",
                            QuyenId = 1,
                            Ten = "admin"
                        });
                });

            modelBuilder.Entity("PrisonManagement.Models.ThamGap", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CMND")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("GhiChu")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("NgayThamGap")
                        .HasColumnType("datetime2");

                    b.Property<string>("NguoiThamGap")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NoiDungTiepTe")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("PhamNhanId")
                        .HasColumnType("int");

                    b.Property<string>("QuanHe")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<TimeSpan?>("ThoiGianBatDau")
                        .HasColumnType("time");

                    b.Property<TimeSpan?>("ThoiGianKetThuc")
                        .HasColumnType("time");

                    b.HasKey("Id");

                    b.HasIndex("PhamNhanId");

                    b.ToTable("ThamGap");
                });

            modelBuilder.Entity("PrisonManagement.Models.CanBo", b =>
                {
                    b.HasOne("PrisonManagement.Models.TaiKhoan", "TaiKhoan")
                        .WithOne("CanBo")
                        .HasForeignKey("PrisonManagement.Models.CanBo", "TaiKhoanId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("TaiKhoan");
                });

            modelBuilder.Entity("PrisonManagement.Models.KhenThuong", b =>
                {
                    b.HasOne("PrisonManagement.Models.PhamNhan", "PhamNhan")
                        .WithMany("KhenThuongs")
                        .HasForeignKey("PhamNhanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PhamNhan");
                });

            modelBuilder.Entity("PrisonManagement.Models.KyLuat", b =>
                {
                    b.HasOne("PrisonManagement.Models.PhamNhan", "PhamNhan")
                        .WithMany("KyLuats")
                        .HasForeignKey("PhamNhanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PhamNhan");
                });

            modelBuilder.Entity("PrisonManagement.Models.LaoDong", b =>
                {
                    b.HasOne("PrisonManagement.Models.PhamNhan", "PhamNhan")
                        .WithMany("LaoDongs")
                        .HasForeignKey("PhamNhanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PhamNhan");
                });

            modelBuilder.Entity("PrisonManagement.Models.LichSuTruyCap", b =>
                {
                    b.HasOne("PrisonManagement.Models.TaiKhoan", "TaiKhoan")
                        .WithMany()
                        .HasForeignKey("TaiKhoanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TaiKhoan");
                });

            modelBuilder.Entity("PrisonManagement.Models.PhamNhan", b =>
                {
                    b.HasOne("PrisonManagement.Models.PhongGiam", "PhongGiam")
                        .WithMany("PhamNhans")
                        .HasForeignKey("PhongGiamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("PhongGiam");
                });

            modelBuilder.Entity("PrisonManagement.Models.SucKhoe", b =>
                {
                    b.HasOne("PrisonManagement.Models.PhamNhan", "PhamNhan")
                        .WithMany("SucKhoes")
                        .HasForeignKey("PhamNhanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PhamNhan");
                });

            modelBuilder.Entity("PrisonManagement.Models.TaiKhoan", b =>
                {
                    b.HasOne("PrisonManagement.Models.Quyen", "Quyen")
                        .WithMany("TaiKhoans")
                        .HasForeignKey("QuyenId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Quyen");
                });

            modelBuilder.Entity("PrisonManagement.Models.ThamGap", b =>
                {
                    b.HasOne("PrisonManagement.Models.PhamNhan", "PhamNhan")
                        .WithMany("ThamGaps")
                        .HasForeignKey("PhamNhanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PhamNhan");
                });

            modelBuilder.Entity("PrisonManagement.Models.PhamNhan", b =>
                {
                    b.Navigation("KhenThuongs");

                    b.Navigation("KyLuats");

                    b.Navigation("LaoDongs");

                    b.Navigation("SucKhoes");

                    b.Navigation("ThamGaps");
                });

            modelBuilder.Entity("PrisonManagement.Models.PhongGiam", b =>
                {
                    b.Navigation("PhamNhans");
                });

            modelBuilder.Entity("PrisonManagement.Models.Quyen", b =>
                {
                    b.Navigation("TaiKhoans");
                });

            modelBuilder.Entity("PrisonManagement.Models.TaiKhoan", b =>
                {
                    b.Navigation("CanBo");
                });
#pragma warning restore 612, 618
        }
    }
}
